(()=>{
  const cfg=window.APP_CONFIG,levels=window.GAME_LEVELS,key=window.ANSWER_KEY,questions=levels.flatMap(l=>l.questions);
  let password='',allResponses=[],viewRows=[],timer;
  const $=s=>document.querySelector(s),toast=$('#toast');
  const demo=!cfg.apiUrl||cfg.apiUrl.includes('PASTE_YOUR_');
  $('#demoHint').textContent=demo?'目前是預覽模式：輸入任意密碼，可看到同一瀏覽器送出的測試資料。':'';

  function esc(v=''){return String(v).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
  function show(m){toast.textContent=m;toast.classList.add('show');clearTimeout(show.t);show.t=setTimeout(()=>toast.classList.remove('show'),1800)}
  async function api(p){if(demo)return{ok:true,responses:JSON.parse(localStorage.getItem(cfg.demoStorageKey)||'[]')};const r=await fetch(cfg.apiUrl,{method:'POST',redirect:'follow',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(p)}),t=await r.text();let d;try{d=JSON.parse(t)}catch{throw new Error('API 回傳格式錯誤')}if(!d.ok)throw new Error(d.error||'讀取失敗');return d}
  function score(r){let c=0,t=0;Object.entries(key).forEach(([id,a])=>{t++;if(r.answers?.[id]===a)c++});return{c,t,p:t?c/t*100:0}}
  function vals(list,id){return list.map(r=>r.answers?.[id]).flatMap(v=>Array.isArray(v)?v:[v]).filter(v=>v!==undefined&&v!==null&&String(v)!=='')}
  function counts(arr){const m=new Map;arr.forEach(v=>m.set(String(v),(m.get(String(v))||0)+1));return[...m.entries()].sort((a,b)=>b[1]-a[1])}
  function chart(el,entries,total){$(el).innerHTML=entries.length?entries.map(([l,c])=>`<div class="chart-row"><div class="chart-top"><span>${esc(l)}</span><span>${c} · ${total?Math.round(c/total*100):0}%</span></div><div class="chart-bar"><i style="width:${total?Math.min(100,c/total*100):0}%"></i></div></div>`).join(''):'<p class="helper">尚無資料</p>'}
  function avg(a){a=a.map(Number).filter(Number.isFinite);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null}
  function catalog(){return Array.isArray(cfg.academicCatalog)?cfg.academicCatalog:[]}
  function option(value,label){return `<option value="${esc(value)}">${esc(label)}</option>`}
  function selected(){return{termId:$('#termSelect').value,courseId:$('#courseSelect').value,classId:$('#classSelect').value}}
  function termById(id){return catalog().find(t=>t.id===id)}
  function coursesFor(termId){if(termId){return termById(termId)?.courses||[]}const seen=new Map;catalog().flatMap(t=>t.courses||[]).forEach(c=>{if(!seen.has(c.id))seen.set(c.id,c)});return[...seen.values()]}
  function classesFor(termId,courseId){const out=[],seen=new Set;catalog().forEach(t=>{if(termId&&t.id!==termId)return;(t.courses||[]).forEach(c=>{if(courseId&&c.id!==courseId)return;(c.classes||[]).forEach(k=>{const key=`${k.id}|${k.label}`;if(!seen.has(key)){seen.add(key);out.push(k)}})})});return out}
  function fillTerms(){const cur=$('#termSelect').value;$('#termSelect').innerHTML=option('','全部學期')+catalog().map(t=>option(t.id,t.label)).join('');if([...$('#termSelect').options].some(o=>o.value===cur))$('#termSelect').value=cur}
  function fillCourses(){const cur=$('#courseSelect').value,termId=$('#termSelect').value;const list=coursesFor(termId);$('#courseSelect').innerHTML=option('','全部課程')+list.map(c=>option(c.id,c.label)).join('');if([...$('#courseSelect').options].some(o=>o.value===cur))$('#courseSelect').value=cur;else $('#courseSelect').value=''}
  function fillClasses(){const cur=$('#classSelect').value,{termId,courseId}=selected();const list=classesFor(termId,courseId);$('#classSelect').innerHTML=option('','全部班級')+list.map(c=>option(c.id,c.label)).join('');if([...$('#classSelect').options].some(o=>o.value===cur))$('#classSelect').value=cur;else $('#classSelect').value=''}
  function labelsForSelection(){const {termId,courseId,classId}=selected();const t=catalog().find(x=>x.id===termId);const c=(t?.courses||coursesFor('')).find(x=>x.id===courseId);const k=(c?.classes||classesFor(termId,courseId)).find(x=>x.id===classId);return{term:t?.label||'',course:c?.label||'',cls:k?.label||''}}
  function currentResponses(){const {termId,courseId,classId}=selected();return allResponses.filter(r=>(!termId||r.termId===termId)&&(!courseId||r.courseId===courseId)&&(!classId||r.classId===classId))}
  function updateScope(){const sel=selected(),lab=labelsForSelection(),parts=[lab.term||'全部學期',lab.course||'全部課程',lab.cls||'全部班級'];$('#activeScope').textContent=parts.join(' → ');const exact=sel.termId&&sel.courseId&&sel.classId;const link=$('#studentLink'),btn=$('#copyLinkBtn');if(exact){const base=new URL('index.html',location.href);base.search='';base.searchParams.set('term',sel.termId);base.searchParams.set('course',sel.courseId);base.searchParams.set('class',sel.classId);link.textContent=base.href;link.dataset.url=base.href;btn.disabled=false}else{link.textContent='選定一個學期、課程與班級後，這裡會產生專屬網址。';link.dataset.url='';btn.disabled=true}}
  function render(){const responses=currentResponses(),n=responses.length;$('#kResponses').textContent=n;$('#kPower').textContent=n?Math.round(responses.filter(r=>r.answers?.ai_frequency==='已經是工作／學習的重要工具').length/n*100)+'%':'0%';const a=avg(responses.map(r=>score(r).p));$('#kAccuracy').textContent=a===null?'—':Math.round(a)+'%';const s=avg(responses.map(r=>r.answers?.self_design));$('#kSelf').textContent=s===null?'—':s.toFixed(1);chart('#freq',counts(vals(responses,'ai_frequency')),n);chart('#tools',counts(vals(responses,'ai_tools')),n);const weak=Object.entries(key).map(([id,ans])=>{const q=questions.find(q=>q.id===id);const answered=responses.filter(r=>r.answers?.[id]!==undefined);const correct=answered.filter(r=>r.answers?.[id]===ans).length;return[q?.label||id,answered.length?Math.round((1-correct/answered.length)*100):0]}).sort((a,b)=>b[1]-a[1]).slice(0,5);chart('#weak',weak,100);chart('#concerns',counts(vals(responses,'course_concern')),n);const wishes=responses.filter(r=>r.answers?.want_to_build).sort((a,b)=>new Date(b.submittedAt)-new Date(a.submittedAt));$('#wishes').innerHTML=wishes.length?wishes.slice(0,30).map(r=>`<div class="wish-card"><div class="wish-meta">${esc(r.termLabel||'')} · ${esc(r.courseLabel||'')} · ${esc(r.classLabel||'未分類')}</div><b>${esc(r.name||'匿名')}</b>：${esc(r.answers.want_to_build)}${(r.answers.wish_tags||[]).length?`<div class="helper">${r.answers.wish_tags.map(esc).join(' · ')}</div>`:''}</div>`).join(''):'<p class="helper">還沒有願望投入願望機。</p>';rows();updateScope();$('#updated').textContent='更新時間 '+new Date().toLocaleTimeString('zh-TW',{hour12:false})}
  function rows(){const needle=$('#filter').value.trim().toLowerCase();viewRows=currentResponses().filter(r=>String(r.name||'').toLowerCase().includes(needle)).sort((a,b)=>new Date(b.submittedAt)-new Date(a.submittedAt));$('#rowCount').textContent=`目前顯示 ${viewRows.length} 人`;$('#rows').innerHTML=viewRows.map((r,i)=>{const s=score(r);return`<tr><td>${esc(r.classLabel||'未分類')}</td><td><b>${esc(r.name||'—')}</b></td><td>${r.submittedAt?new Date(r.submittedAt).toLocaleString('zh-TW'):'—'}</td><td>${esc(r.answers?.ai_frequency||'—')}</td><td>${r.xp||0}</td><td>${s.c}/${s.t}</td><td><button class="ghost-btn" data-view="${i}">查看</button></td></tr>`}).join('');document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>open(Number(b.dataset.view))))}
  function open(i){const r=viewRows[i];if(!r)return;$('#modalTitle').textContent=(r.name||'未命名')+'｜作答明細';const context=`${r.termLabel||'未分類學期'} → ${r.courseLabel||'未分類課程'} → ${r.classLabel||'未分類班級'}`;$('#modalBody').innerHTML=`<div class="answer-row"><b>班級路徑</b><div>${esc(context)}</div></div>`+questions.map(q=>{const v=r.answers?.[q.id];return`<div class="answer-row"><b>${esc(q.label||q.prompt||q.id)}</b><div>${esc(Array.isArray(v)?v.join('、'):(v??'—'))}</div></div>`}).join('');$('#modal').classList.remove('hidden')}
  async function refresh(silent=false){try{const d=await api({action:'list',password,formVersion:cfg.formVersion});allResponses=Array.isArray(d.responses)?d.responses:[];render();if(!silent)show('已更新')}catch(e){show(e.message);throw e}}
  function csv(){const responses=currentResponses();if(!responses.length){show('目前篩選範圍沒有資料');return}const heads=['學期','課程','班級','姓名','送出時間','XP',...questions.map(q=>q.label||q.prompt||q.id),'答對','總題'];const data=responses.map(r=>{const s=score(r);return[r.termLabel||r.termId,r.courseLabel||r.courseId,r.classLabel||r.classId,r.name,r.submittedAt,r.xp,...questions.map(q=>r.answers?.[q.id]),s.c,s.t]});const eq=v=>{const s=Array.isArray(v)?v.join(' | '):String(v??'');return/[",\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s};const text='\ufeff'+[heads,...data].map(row=>row.map(eq).join(',')).join('\n');const blob=new Blob([text],{type:'text/csv;charset=utf-8'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;const sel=labelsForSelection();a.download=`ai-university-${sel.cls||'all'}-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(u)}
  function filtersChanged(){fillCourses();fillClasses();render()}

  fillTerms();fillCourses();fillClasses();updateScope();
  $('#termSelect').addEventListener('change',filtersChanged);
  $('#courseSelect').addEventListener('change',()=>{fillClasses();render()});
  $('#classSelect').addEventListener('change',render);
  $('#copyLinkBtn').addEventListener('click',async()=>{const u=$('#studentLink').dataset.url;if(!u)return;try{await navigator.clipboard.writeText(u);show('學生專屬網址已複製')}catch{show('無法自動複製，請手動選取網址')}});
  $('#loginBtn').addEventListener('click',async()=>{password=$('#password').value.trim();if(!password&&!demo){show('請輸入教師密碼');return}try{await refresh(true);$('#login').classList.add('hidden');$('#dashboard').classList.remove('hidden');timer=setInterval(()=>refresh(true).catch(()=>{}),cfg.teacherRefreshSeconds*1000)}catch{}});
  $('#password').addEventListener('keydown',e=>{if(e.key==='Enter')$('#loginBtn').click()});
  $('#refreshBtn').addEventListener('click',()=>refresh().catch(()=>{}));
  $('#exportBtn').addEventListener('click',csv);
  $('#filter').addEventListener('input',rows);
  $('#closeModal').addEventListener('click',()=>$('#modal').classList.add('hidden'));
  $('#modal').addEventListener('click',e=>{if(e.target.id==='modal')$('#modal').classList.add('hidden')});
})();
